ДЗ 1. Создать проект на GitHub
SupBaam/baampplication pull request #1
Opened 2021-11-27 20:14 UTC by SupBaam

1. Создал репозиторий с одним ридми 
2. Создал клон репозитория 
3. через нью проджект создал пустую активность в репозитории 
4. создал ветку под дз
5. коммит-пуш

АС ругался на ошибки после создания активности 
![image](https://user-images.githubusercontent.com/92381002/143720975-913ad915-707c-4925-b009-096a1f4ddbe4.png)
![image](https://user-images.githubusercontent.com/92381002/143720979-89925563-afc8-49ad-8d0d-303406504708.png)
![image](https://user-images.githubusercontent.com/92381002/143720985-c9da6273-b15e-4824-9d74-a8b33bc41cb8.png)

2021-12-06 18:54 UTC, VadimB95 requested changes
жду исправления

2021-12-06 18:54 UTC, VadimB95 commented on .gitignore
> +/.idea/caches
удали папку `.idea` целиком из репозитория

2021-12-08 14:36 UTC, SupBaam commented on .gitignore
> +/.idea/caches
Исправил

2021-12-08 18:18 UTC, VadimB95 commented on .gitignore
> +/.idea/caches
пересмотри требования к оформлению пр. 
https://classroom.google.com/c/NDAwOTA0OTgzOTAw/m/NDAyMjU4MzU2NjMy/details
один из пунктов заключается в том, что пр должен быть с одним коммитом. поэтому тебе надо засквошить твои коммиты локально и сделать форс пуш в удаленную ветку

2021-12-08 18:21 UTC, VadimB95 requested changes

2021-12-08 18:21 UTC, VadimB95 commented on README.md
> +Обязательные требования к оформлению PR:
а зачем это сюда добавил?) тут должно быть только то, что сделал в рамках выполнения задания

2021-12-09 04:58 UTC, VadimB95 commented on README.md
> +- Есть заголовок PR
удали это всё. пусть останется только первая строка

2021-12-09 05:01 UTC, VadimB95 commented
еще добавь меня пожалуйста в контрибьютеры, видимо я поздно нажал принять, и приглашение устарело

2021-12-09 16:44 UTC, SupBaam commented
Добавил в контрибьютеры
Засквошил исправления  в один коммит

2021-12-10 05:28 UTC, VadimB95 approved these changes

2021-12-10 05:29 UTC, merged